### ISSUE TITLE
「バインドできませんでした」エラー

### ISSUE THREAD

**Issue by Name2889** [s1204IT/DchaServiceTester#1]
こんにちは。Neo(TAB-A05-BD)にadbにてインストールしましたが、開いたときに「DchaServiceをバインドできませんでした」とエラーが出ています。解決方法を教えていただけますでしょうか。
Nova Launcherがインストール済みです。
お忙しいところ恐縮ですが、
よろしくお願いいたします。

**Comment by s1204IT** [comment]
**DchaService** がアンインストールされています。

以下のコマンドを実行して、**DchaService** を復元してください
```
adb shell cmd package install-existing jp.co.benesse.dcha.dchaservice
```

**Comment by Name2889** [comment]
ありがとうございます。助かりました。
よろしくお願いいたします。
